<h3><?=$product['name']?></h3>
<img src="<?=CLIENT_ROOT?>/ressources/images/<?=$product['imagePath']?>" alt="">
<p><?=$product['description']?></p>
<p><?=$product['priceTTC']?> €<!-- $ <a href="<?=CLIENT_ROOT?>/panier/ajouter/?id=<?=$product['id']?>">Ajouter au panier</a>--></p>
<form action="<?=CLIENT_ROOT?>/panier/ajouter/?id=<?=$product['id']?>" method="post">
	<label for="">Ajouter au panier</label>
	<input type="number" name="quantite" value="1" placeholder="quantité">
	<input type="submit">
</form>
