
	
	<div class="clearfix creation">
		<h3>Création de compte</h3>
		<form action="" method="post">
			<div class="clearfix">
				<label  for="civility">Civilité</label>
				<select  id="civility" name="civility">
					<option value="M.">M.</option>
					<option value="Mme">Mme</option>
					<option value="Mlle">Mlle</option>
				</select>
			</div>
			<div class="clearfix">
				<label  for="firstName">Prénom</label>
				<input  type="text" id="firstName" name="firstName" placeholder="prenom">
			</div>
			<div class="clearfix">
				<label for="lastName">Nom</label>
				<input type="text" id="lastName" name="lastName" placeholder="nom">
			</div>
			<div class="clearfix">
				<label  for="email">E-mail</label>
				<input  type="text" id="email" name="email" placeholder="email" required>
			</div>

			<div class="clearfix">
				<label for="password">Mot de passe</label>
				<input type="password" id="password" name="password" placeholder="mot de passe">
			</div>
			
			<input class="valid" type="submit">
		
		</form>

	</div>

